#!/bin/bash
# Bare repository directory.
GIT_DIR="/var/www/myproject-git"
# Target directory.
TARGET="/var/www/myproject"
while read oldrev newrev ref
do
    BRANCH=$(git rev-parse --symbolic --abbrev-ref $ref)
    if [[ $BRANCH == "main" ]]; then
        echo "Push received! Deploying branch: ${BRANCH}..."
        # deploy to our target directory.
        git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
    else
        echo "Not main branch. Skipping."
    fi
done
