name: Deploy Project

on: 
  push:
    branches: 
      - main

jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@v1.2.2
      with: 
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        password: ${{secrets.SERVER_USER_PASSWORD}}
        passphrase: ${{secrets.SSH_PASSWORD}}
        script: |
          cd ${{ secrets.REPO_PATH }}
          git pull origin main

        

    
