name: Deploy Project

on: 
  push:
    branches: 
      - main

jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # - name: Get SSH key and set permissions
    #   run: |
    #     mkdir -p ~/.ssh
    #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    #     chmod 600 ~/.ssh/id_rsa
    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@v1.2.2
      with: 
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        password: ${{secrets.SERVER_USER_PASSWORD}}
        passphrase: ${{secrets.SSH_PASSWORD}}
        script: |
          cd /var/www
          git pull origin main

        

    
